# Generated by Django 5.0.3 on 2024-03-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pen_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
